### ISSUE TITLE
Verifying Issue

### ISSUE THREAD

**Issue by pedroalbanese** [z789/sm3sum#1]
Hi,

The -c function does not work when the files have spaces in the name. It gives error. Only when I use the --tag function to generate the hash file, possibly because there is (parentheses) in BSD format. But when in coreutils format, it bugs.

How to proceed?

Thanks in advance.

**Comment by z789** [comment]
Thanks
Fixed. See commit 7f380394fb544c1d504e3ac35f1f1d051a8818db

**Comment by z789** [comment]
Fixed. See commit 7f38039
